package main

import (
	"context"
	"crypto/sha256"
	"database/sql"
	"encoding/json"
	"fmt"
	"os"
	"strings"
	"time"

	"github.com/jiayu/wbot/internal/backtest"
	"github.com/jiayu/wbot/internal/backtestes"
	"github.com/jiayu/wbot/internal/backtestexec"
	"github.com/jiayu/wbot/internal/backtestreport"
	"github.com/jiayu/wbot/internal/db"
	"github.com/jiayu/wbot/internal/strategy"
)

// repeatedStringFlag keeps the original single -params spelling while also
// accepting repeated flags for fixed-parameter sensitivity runs.
type repeatedStringFlag []string

func (f *repeatedStringFlag) String() string { return strings.Join(*f, ",") }

func (f *repeatedStringFlag) Set(value string) error {
	*f = append(*f, value)
	return nil
}

// parseBacktestParamGroups accepts one object (the historical form), repeated
// objects, or one JSON array of objects. The latter is useful when a shell
// command is generated by another tool and avoids shell quoting per group.
func parseBacktestParamGroups(raw []string) ([]map[string]any, error) {
	if len(raw) == 0 {
		return []map[string]any{{}}, nil
	}
	if len(raw) == 1 && strings.TrimSpace(raw[0]) == "" {
		// Preserve the historical `-params ""` spelling: it meant no params.
		return []map[string]any{{}}, nil
	}
	groups := make([]map[string]any, 0, len(raw))
	for _, encoded := range raw {
		encoded = strings.TrimSpace(encoded)
		if encoded == "" {
			return nil, fmt.Errorf("JSON must not be empty")
		}
		if strings.HasPrefix(encoded, "[") {
			var batch []map[string]any
			if err := json.Unmarshal([]byte(encoded), &batch); err != nil {
				return nil, err
			}
			if len(batch) == 0 {
				return nil, fmt.Errorf("JSON parameter array must contain at least one object")
			}
			groups = append(groups, batch...)
			continue
		}
		var params map[string]any
		if err := json.Unmarshal([]byte(encoded), &params); err != nil {
			return nil, err
		}
		groups = append(groups, params)
	}
	return groups, nil
}

type backtestBatchFlags struct {
	Save          bool
	Report        bool
	ReportDir     string
	Push          bool
	MaxDrawdown   float64
	Symbol        string
	Strategy      string
	ConfigVersion *int
	Options       backtestexec.Options
}

type fixedBacktestResult struct {
	Params            map[string]any
	Result            *backtest.Result
	StartTs           time.Time
	EndTs             time.Time
	BaselineReturnPct float64
	SourceHash        string
}

// runBacktestBatch evaluates fixed parameter groups over one shared input
// snapshot. DB runs use backtestexec.Prepare once; file runs parse bars once.
// Both paths use the same ordered 8-worker pool.
func runBacktestBatch(dsn, file, symbol, strategyName string, groups []map[string]any, baseOpts backtestexec.Options, flags backtestBatchFlags) int {
	if len(groups) < 2 {
		return 2
	}
	if flags.ConfigVersion != nil {
		fmt.Fprintln(os.Stderr, "backtest: multiple -params groups cannot use a versioned watchlist config")
		return 2
	}

	ctx := context.Background()
	tasks := make([]func(context.Context) (fixedBacktestResult, error), len(groups))
	var database *sql.DB
	var prepared *backtestexec.Prepared
	var sourceHash string
	var startTs, endTs time.Time
	var baselineReturnPct float64

	if strings.TrimSpace(file) != "" {
		data, err := os.ReadFile(file)
		if err != nil {
			fmt.Fprintf(os.Stderr, "backtest: read %s: %v\n", file, err)
			return 1
		}
		digest := sha256.Sum256(data)
		sourceHash = fmt.Sprintf("sha256-%x", digest)
		parsed, err := backtest.ParseBars(data)
		if err != nil {
			fmt.Fprintf(os.Stderr, "backtest: %v\n", err)
			return 1
		}
		startTs, endTs = parsed[0].Ts, parsed[len(parsed)-1].Ts
		baselineReturnPct = parsed[len(parsed)-1].Close/parsed[0].Close - 1
		for i, params := range groups {
			params, index := params, i
			tasks[index] = func(taskCtx context.Context) (fixedBacktestResult, error) {
				s, _, err := backtestexec.Build(strategyName, params)
				if err != nil {
					return fixedBacktestResult{}, err
				}
				res, err := backtest.RunOptions(taskCtx, parsed, baseOpts.Cash, baseOpts.Fee, s, &backtest.OptionsData{RunSeed: baseOpts.Seed})
				if err != nil {
					return fixedBacktestResult{}, err
				}
				return fixedBacktestResult{Params: params, Result: res, StartTs: startTs, EndTs: endTs,
					BaselineReturnPct: baselineReturnPct, SourceHash: sourceHash}, nil
			}
		}
	} else {
		var err error
		database, err = db.Open(dsn)
		if err != nil {
			fmt.Fprintf(os.Stderr, "backtest: open db: %v\n", err)
			return 1
		}
		defer database.Close()
		if err := db.MigrateUp(database); err != nil {
			fmt.Fprintf(os.Stderr, "backtest: migrate: %v\n", err)
			return 1
		}
		prepared, err = backtestexec.Prepare(ctx, database, baseOpts)
		if err != nil {
			fmt.Fprintf(os.Stderr, "backtest: batch preparation: %v\n", err)
			return 1
		}
		for i, params := range groups {
			params, index := params, i
			tasks[index] = func(taskCtx context.Context) (fixedBacktestResult, error) {
				runOpts := baseOpts
				runOpts.Params = params
				out, err := prepared.RunPrepared(taskCtx, runOpts)
				if err != nil {
					return fixedBacktestResult{}, err
				}
				return fixedBacktestResult{Params: params, Result: out.Result, StartTs: out.StartTs, EndTs: out.EndTs,
					BaselineReturnPct: out.BaselineReturnPct, SourceHash: out.SourceHash}, nil
			}
		}
	}

	results, err := backtestes.ParallelMap(ctx, tasks)
	if err != nil {
		fmt.Fprintf(os.Stderr, "backtest: fixed-parameter evaluation: %v\n", err)
		return 1
	}
	fmt.Printf("fixed_params=%d workers=%d\n", len(results), backtestes.EvaluationWorkers)
	for i, item := range results {
		paramsJSON, err := json.Marshal(item.Params)
		if err != nil {
			fmt.Fprintf(os.Stderr, "backtest: fixed-parameter params %d: %v\n", i+1, err)
			return 1
		}
		printFixedBacktestSummary(i, paramsJSON, item.Result)
	}

	exitCode := 0
	for i, item := range results {
		if flags.MaxDrawdown > 0 && item.Result.MaxDrawdown > flags.MaxDrawdown {
			fmt.Fprintf(os.Stderr, "backtest: params[%d] max drawdown %v exceeds limit %v\n", i, item.Result.MaxDrawdown, flags.MaxDrawdown)
			exitCode = 1
		}
		if flags.Save {
			if database == nil {
				fmt.Fprintln(os.Stderr, "backtest: -save requires -dsn input")
				return 2
			}
			saveOpts := flags.Options
			saveOpts.Params = item.Params
			id, err := backtest.SaveResult(context.Background(), database, strategyName, symbol,
				backtestexec.SaveParams(saveOpts), item.Result, item.StartTs, item.EndTs)
			if err != nil {
				fmt.Fprintf(os.Stderr, "backtest: params[%d] save: %v\n", i, err)
				return 1
			}
			fmt.Printf("params[%d] saved result id=%d\n", i, id)
		}
		if flags.Report {
			rep, err := buildFixedBacktestReport(item, flags)
			if err != nil {
				fmt.Fprintf(os.Stderr, "backtest: params[%d] report: %v\n", i, err)
				return 1
			}
			jsonPath, htmlPath, err := backtestreport.Write(strings.TrimSpace(flags.ReportDir), rep)
			if err != nil {
				fmt.Fprintf(os.Stderr, "backtest: params[%d] report: %v\n", i, err)
				return 1
			}
			fmt.Printf("params[%d] report_id=%s json=%s html=%s\n", i, rep.ReportID, jsonPath, htmlPath)
			if flags.Push {
				status, pushErr := pushBacktestReport(context.Background(), rep)
				if pushErr != nil {
					fmt.Fprintf(os.Stderr, "backtest: params[%d] push: %v\n", i, pushErr)
					exitCode = 1
				} else {
					fmt.Printf("params[%d] push_status=%s report_id=%s\n", i, status, rep.ReportID)
				}
			}
		}
	}
	return exitCode
}

func printFixedBacktestSummary(index int, paramsJSON []byte, res *backtest.Result) {
	if res.Unfilled.AttemptCount == 0 {
		fmt.Printf("params[%d] params=%s final_equity=%v total_return=%v max_drawdown=%v bars=%d fees=%v 未成交 N/A(无成交尝试)\n", index, paramsJSON, res.Equity, res.TotalReturn, res.MaxDrawdown, res.Bars, res.Fees.TotalAmount)
		return
	}
	fmt.Printf("params[%d] params=%s final_equity=%v total_return=%v max_drawdown=%v bars=%d fees=%v 未成交 %d/%d (%.2f%%)\n", index, paramsJSON, res.Equity, res.TotalReturn, res.MaxDrawdown, res.Bars, res.Fees.TotalAmount, res.Unfilled.UnfilledCount, res.Unfilled.AttemptCount, *res.Unfilled.UnfilledRatio*100)
}

func buildFixedBacktestReport(item fixedBacktestResult, flags backtestBatchFlags) (*backtestreport.Report, error) {
	params := item.Params
	migrationLossy := false
	var originalJSON json.RawMessage
	if flags.Strategy == "wheel" {
		canonical, err := strategy.CanonicalParams(params)
		if err != nil {
			return nil, err
		}
		params = canonical
		cfg, err := strategy.ParseConfig(item.Params)
		if err != nil {
			return nil, err
		}
		migrationLossy = cfg.MigrationLossy
		if migrationLossy {
			originalJSON, err = json.Marshal(item.Params)
			if err != nil {
				return nil, err
			}
		}
	}
	return backtestreport.Build(backtestreport.Input{
		Symbol: flags.Symbol, Strategy: flags.Strategy, Params: params, ConfigVersion: flags.ConfigVersion,
		CodeVersion: version, RunSeed: flags.Options.Seed, InitialCash: flags.Options.Cash, FeePerTrade: flags.Options.Fee,
		Start: item.StartTs, End: item.EndTs, BaselineReturnPct: item.BaselineReturnPct,
		SourceHash: item.SourceHash, MigrationLossy: migrationLossy, OriginalJSON: originalJSON,
		Result: item.Result,
	})
}
